### PR TITLE
Added a script to generate the structure for aea components.

### PR DESCRIPTION
**Pull request by l-wegner**

### CODE REVIEW

**Comment by danielksan81** [comment]
Hi @l-wegner, can you add yourself to the NOTICE file as this is your first contribution/commit, so you are in the list included?

**Comment by danielksan81** [comment]
Executing the command creates only the corresponding project folder with a Pipfile included. The script exits with an error as it seems.

python3 cli.py test                                                                                                        2 ↵
creating /mnt/dev/aea/aea-test/open-eot-agents/aea_components/test_aea_project/Pipfile
running pipenv update at /mnt/dev/aea/aea-test/open-eot-agents/aea_components/test_aea_project
=== begin output: ['pipenv', 'update']
Traceback (most recent call last):
  File "cli.py", line 142, in <module>
    main(sys.argv)
  File "cli.py", line 138, in main
    scaffold_module(argv[1])
  File "cli.py", line 117, in scaffold_module
    setup_pipenv(component_project_dir)
  File "cli.py", line 67, in setup_pipenv
    run_command_in_subprocess(["pipenv", "update"], component_project_dir)
  File "cli.py", line 85, in run_command_in_subprocess
    preexec_fn=os.setsid
TypeError: __init__() got an unexpected keyword argument 'text'

**Comment by l-wegner** [comment]
> 
> 
> Executing the command creates only the corresponding project folder with a Pipfile included. The script exits with an error as it seems.
> 
> python3 cli.py test 2 ↵ creating /mnt/dev/aea/aea-test/open-eot-agents/aea_components/test_aea_project/Pipfile running pipenv update at /mnt/dev/aea/aea-test/open-eot-agents/aea_components/test_aea_project === begin output: ['pipenv', 'update'] Traceback (most recent call last): File "cli.py", line 142, in main(sys.argv) File "cli.py", line 138, in main scaffold_module(argv[1]) File "cli.py", line 117, in scaffold_module setup_pipenv(component_project_dir) File "cli.py", line 67, in setup_pipenv run_command_in_subprocess(["pipenv", "update"], component_project_dir) File "cli.py", line 85, in run_command_in_subprocess preexec_fn=os.setsid TypeError: **init**() got an unexpected keyword argument 'text'

This seems to be a python version problem. I was not aware, that there were changes in that package recently. Do you use Python 3.7 or higher?

**Comment by danielksan81** [comment]
Running it with python 3.7 leads to

python3.7 cli.py test
creating /mnt/dev/aea/aea-test/open-eot-agents/aea_components/test_aea_project/Pipfile
running pipenv update at /mnt/dev/aea/aea-test/open-eot-agents/aea_components/test_aea_project
=== begin output: ['pipenv', 'update']
Warning: Python 3.8 was not found on your system…
Neither 'pyenv' nor 'asdf' could be found to install Python.
You can specify specific versions of Python with:
$ pipenv --python path/to/python
Traceback (most recent call last):
  File "cli.py", line 142, in <module>
    main(sys.argv)
  File "cli.py", line 138, in main
    scaffold_module(argv[1])
  File "cli.py", line 117, in scaffold_module
    setup_pipenv(component_project_dir)
  File "cli.py", line 67, in setup_pipenv
    run_command_in_subprocess(["pipenv", "update"], component_project_dir)
  File "cli.py", line 94, in run_command_in_subprocess
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['pipenv', 'update']' returned non-zero exit status 1.

**Comment by danielksan81** [comment]
is it needed to use python3.8 as default?

**Comment by l-wegner** [comment]
> You can specify specific versions of Python with:
> $ pipenv --python path/to/python
> Traceback (most recent call last):
> File "cli.py", line 142, in
> main(sys.argv)
> File "cli.py", line 138, in main
> scaffold_module(argv[1])
> File "cli.py", line 117, in scaffold_module
> setup_pipenv(component_project_dir)
> File "cli.py", line 67, in setup_pipenv
> run_command_in_subprocess(["pipenv", "update"], component_project_dir)
> File "cli.py", line 94, in run_command_in_subprocess

The problem now is, that pipenv is not installed.
This is a TODO, to check for it.
`pip install --user pipenv`

**Comment by danielksan81** [comment]
After switching to python 3.8 and installing pipenv everything seems to work.
Should these requirements be added to the readme as well?

**Comment by l-wegner** [comment]
> 
> 
> After switching to python 3.8 and installing pipenv everything seems to work. Should these requirements be added to the readme as well?

Yes. I documented it now.
And I misread your last error, which did not complain about pipenv missing. But pipenv complained about python 3.8 not being available.

**Pull request merged**
